version: '3.1'

services:

  ghost:
    image: ghost:3-alpine
    restart: always
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    environment:
      server__host: ${SERVER_HOST}
      server__port: ${SERVER_PORT}
      database__client: mysql
      database__connection__host: db
      database__connection__database: ${DB_DATABASE}
      database__connection__user: ${DB_USER}
      database__connection__password: ${DB_PASSWORD}

  db:
    image: mysql:5.7
    environment: 
      - MYSQL_ROOT_PASSWORD=SECRET
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci